on:
  push:
    branches: ["master", "tokio-*.x"]
  pull_request:
    branches: ["master", "tokio-*.x"]

name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1
  RUSTUP_WINDOWS_PATH_ADD_BIN: 1
  # Change to specific Rust release to pin
  rust_stable: stable
  rust_nightly: nightly-2025-01-25
  # Pin a specific miri version
  rust_miri_nightly: nightly-2025-01-25
  rust_clippy: '1.77'
  # When updating this, also update:
  # - README.md
  # - tokio/README.md
  # - CONTRIBUTING.md
  # - tokio/Cargo.toml
  # - tokio-util/Cargo.toml
  # - tokio-test/Cargo.toml
  # - tokio-stream/Cargo.toml
  rust_min: '1.70'

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  wasm32-unknown-unknown:
    name: test tokio for wasm32-unknown-unknown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust 1.81
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.81
      - name: Install wasm-pack
        uses: taiki-e/install-action@wasm-pack

      - uses: Swatinem/rust-cache@v2
      - name: test tokio
        run: wasm-pack test --node -- --features "macros sync rt" --test rt_wasm
        working-directory: tokio
